
USE `cert`;

DROP TABLE IF EXISTS `cert_fp`;
DROP TABLE IF EXISTS `cert_search`;

ALTER TABLE `cert`
DROP PRIMARY KEY;

ALTER TABLE `cert`
ADD COLUMN `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE `cert`
DROP COLUMN `cert_hash`;
