
-- 创建 cag 数据库
DROP DATABASE IF EXISTS `cag`;
CREATE DATABASE IF NOT EXISTS `cag` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `cag`;

DROP TABLE IF EXISTS `cag_node`;

CREATE TABLE IF NOT EXISTS `cag_node` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  `cert_der` MEDIUMBLOB NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `cag_edge`;

CREATE TABLE IF NOT EXISTS `cag_edge` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  `cert_der` MEDIUMBLOB NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
