
USE `authbase`;

CREATE TABLE IF NOT EXISTS `CERT_CHAIN_RELATION` (
  `CERT_ID` varchar(64) CHARACTER SET gbk COLLATE gbk_chinese_ci NOT NULL,
  `CERT_PARENT_ID` varchar(64) CHARACTER SET gbk COLLATE gbk_chinese_ci NOT NULL,
  PRIMARY KEY (`CERT_ID`, `CERT_PARENT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=gbk ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `DOMAIN_TRUST_RELATION` (
  `DOMAIN` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `CERT_ID` varchar(64) NOT NULL,
  `NOT_VALID_BEFORE` datetime NOT NULL,
  `NOT_VALID_AFTER` datetime NOT NULL,
  PRIMARY KEY (`DOMAIN`, `CERT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=gbk ROW_FORMAT=DYNAMIC;
