
USE `authbase`;

-- CREATE TABLE IF NOT EXISTS `CERT_CHAIN_RELATION` (
--   `CERT_ID` varchar(64) CHARACTER SET gbk COLLATE gbk_chinese_ci NOT NULL,
--   `CERT_PARENT_ID` varchar(64) CHARACTER SET gbk COLLATE gbk_chinese_ci NOT NULL,
--   PRIMARY KEY (`CERT_ID`, `CERT_PARENT_ID`) USING BTREE
-- ) ENGINE=InnoDB DEFAULT CHARSET=gbk ROW_FORMAT=DYNAMIC;

-- CREATE TABLE IF NOT EXISTS `DOMAIN_TRUST_RELATION` (
--   `DOMAIN` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
--   `CERT_ID` varchar(64) NOT NULL,
--   `NOT_VALID_BEFORE` datetime NOT NULL,
--   `NOT_VALID_AFTER` datetime NOT NULL,
--   PRIMARY KEY (`DOMAIN`, `CERT_ID`) USING BTREE
-- ) ENGINE=InnoDB DEFAULT CHARSET=gbk ROW_FORMAT=DYNAMIC;

-- 由于数据较少，暂时不需要进行分区，所以先使用外键
-- cert_store_raw 存储证书的原始PEM数据
CREATE TABLE IF NOT EXISTS `CERT_STORE` (
  `CERT_ID` varchar(64) NOT NULL,
  `CERT_RAW` TEXT NOT NULL,
  PRIMARY KEY (`CERT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=gbk ROW_FORMAT=DYNAMIC;
